// <auto-generated />
namespace Soloveyko_A_V_Geo_Service.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Geo_6 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Geo_6));
        
        string IMigrationMetadata.Id
        {
            get { return "201602281333405_Geo_6"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
